<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Fri, 08 Mar 2019 13:35:37 +0000
 */

$conf['title'] = 'dokuwiki';
$conf['template'] = 'skybs3';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['compress'] = 0;
$conf['tpl']['skybs3']['fixedTopNavbar'] = 1;
$conf['tpl']['skybs3']['fluidContainerBtn'] = 1;

// end auto-generated content
